[package]
name = "zed-uv-extension"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"] }
zed_extension_api = "0.1.0"
